################## Application Settings ####################
server:
  port: ${PORT:8090}

spring:
  config:
    import: "optional:configserver:http://localhost:8091"
  cloud:
    config:
      name: api-gateway,eureka,cloud-bus,springdoc,circuit-breaker
      profile: local
